---
- hosts: localhost
  connection: local
  tasks:
    # order is important (until we implement marathon groups)
    - include: "ci/backends.yml"
    - include: "ci/artifactory.yml"
    - include: "ci/nexus.yml"
    - include: "ci/buildbot.yml"
#    - include: "ci/github_hooks.yml"
