---
- hosts: localhost
  connection: local
  tasks:
    # # order is important (until we implement marathon groups)
    - include: "core/lb.yml"
    - include: "core/metrics.yml"
    - include: "core/logging.yml"
    - include: "core/traefik.yml"
