- vars:
    traefik_conf_path: "/etc/traefik/traefik.toml"
    traefik_conf_url: "{{ zk_http_url }}/{{ traefik_conf_path }}"

  block:
    - name: upload traefik conf in zk
      znode:
        hosts: "{{ zk_host }}"
        name: "{{ traefik_conf_path }}"
        value: "{{ lookup('template', 'traefik/traefik.toml') }}"
        state: present

    - name: "Deploy Traefik Reverse Proxy"
      marathon:
        marathon_uri: "{{ marathon_uri }}"
        group_id: traefik/
        group_json:
          dependencies:
            - /core/lb
            - /core/logging
          apps:
            - id: "router"
              cpus: 2
              mem: 512
              disk: 0
              instances: 1
              args:
                - "--web"
                - "--logLevel=DEBUG"
                - "--configfile=/mnt/mesos/sandbox/traefik.toml"
              container:
                type: DOCKER
                docker:
                  # image: "traefik"
                  image: stibbons31/traefik-workaround-marathon-bad-gateway:workaround_marathon_bad_gateway
                  # network: "HOST"
                  network: "BRIDGE"
                  privileged: true
                  parameters: "{{ docker_log_driver_parameters }}"
                  forcePullImage: false
                  portMappings:
                    - containerPort: 80
                      protocol: tcp
                      hostPort: 80
                      name: "80"
                      servicePort: "{{ servicePorts.traefik_http }}"
                    - containerPort: 19050
                      hostPort: 19050
                      protocol: tcp
                      name: "admin"
                      servicePort: "{{ servicePorts.traefik_admin }}"
              env:
                http_proxy: http://proxy-ir.{{ domain_ext }}:911
                https_proxy: http://proxy-ir.{{ domain_ext }}:911
                no_proxy: 127.0.0.1,localhost,{{ domain_ext }},.{{ domain_ext }},172.17.0.1
                HTTP_PROXY: http://proxy-ir.{{ domain_ext }}:911
                HTTPS_PROXY: http://proxy-ir.{{ domain_ext }}:911
                NO_PROXY: 127.0.0.1,localhost,{{ domain_ext }},.{{ domain_ext }},172.17.0.1
                ALL_PROXY: socks://proxy-ir.{{ domain_ext }}:1080
              healthChecks:
                - path: "/health"
                  protocol: "HTTP"
                  portIndex: 1
                  gracePeriodSeconds: 300
                  intervalSeconds: 60
                  #  timeoutSeconds: 20
                  maxConsecutiveFailures: 3
                  #    ignoreHttp1xx: false
              # residency:
              #   taskLostBehavior: "WAIT_FOREVER"
              # upgradeStrategy:
              #   minimumHealthCapacity: 0.5
              #   maximumOverCapacity: 0
              labels:
                subdomain: 't'
                HAPROXY_GROUP: external
                HAPROXY_BIND_ADDR: 172.17.0.1
                traefik.enable: "false"
              constraints:
                - - hostname
                  - UNIQUE
                - - hostname
                  - LIKE
                  - tlsisbld127l.tl.{{ domain_ext }}
              uris:
                  - "{{ traefik_conf_url }}"
